import { Recipe } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Filters from "y/components/filters";
import Spinner from "y/components/spinner";
import { api } from "y/utils/api";

const Home: NextPage = () => {
  const { data, isLoading } = api.recipe.findTopRated.useQuery({});

  return (
    <>
      <Head>
        <title>Recipme</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Filters />
        <div className="mx-auto max-w-7xl columns-3 space-y-4">
          {isLoading ? (
            <Spinner />
          ) : (
            data?.map((recipe) => (
              <RecipePreviewCard recipe={recipe} key={recipe.id} />
            ))
          )}
        </div>
      </>
    </>
  );
};

const RecipePreviewCard = ({ recipe }: { recipe: Recipe }) => {
  return (
    <div className="card glass h-fit w-[1/3] overflow-hidden rounded-md">
      <figure>
        <img src={recipe.image} alt={recipe.title} class="object-center" />
      </figure>
      <div className="card-body">
        <h2 className="card-title">{recipe.title}</h2>
        <p>{recipe.description}</p>
      </div>
    </div>
  );
};

export default Home;
