import { type NextPage } from "next";
import Head from "next/head";
import Filters from "y/components/filters";
import Spinner from "y/components/spinner";
import { api } from "y/utils/api";

const Home: NextPage = () => {
  const { data, isLoading } = api.recipe.findTopRated.useQuery({});

  return (
    <>
      <Head>
        <title>Recipme</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#c9f5d4] to-[#f3f5c9]">
        <Filters />
        <div className="align-center flex flex-1 flex-col justify-center">
          {isLoading ? (
            <Spinner />
          ) : (
            data?.map((recipe) => <div key={recipe.id}>{recipe.id}</div>)
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
